// <auto-generated />
using System;
using LegalMatterContractPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegalMatterContractPortal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LegalDbContext))]
    partial class LegalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Approval", b =>
                {
                    b.Property<long>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ApprovalId"));

                    b.Property<long?>("ApproverStaffId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatterNumberRef")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Queue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SubjectTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ThresholdAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverStaffId");

                    b.HasIndex("Queue", "Status");

                    b.HasIndex("SubjectType", "SubjectId");

                    b.ToTable("approval", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PrimaryContact")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ClientId");

                    b.HasIndex("Name");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Contract", b =>
                {
                    b.Property<long>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContractId"));

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StageEnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ValueAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("ContractId");

                    b.HasIndex("MatterId");

                    b.HasIndex("RenewalDate");

                    b.HasIndex("Stage");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Deadline", b =>
                {
                    b.Property<long>("DeadlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeadlineId"));

                    b.Property<long?>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeadlineType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OwnerStaffId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("DeadlineId");

                    b.HasIndex("ContractId");

                    b.HasIndex("DueDate");

                    b.HasIndex("MatterId");

                    b.HasIndex("OwnerStaffId");

                    b.HasIndex("Status");

                    b.ToTable("deadline", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<long?>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("UploadedByStaffId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("DocumentId");

                    b.HasIndex("ContractId");

                    b.HasIndex("FolderPath");

                    b.HasIndex("MatterId");

                    b.HasIndex("UploadedByStaffId");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InvoiceId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FirmId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("FirmId");

                    b.HasIndex("InvoiceDate");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("MatterId");

                    b.HasIndex("Status");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<long>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LineItemId"));

                    b.Property<string>("ActivityCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ExpenseCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("FlagReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("LineItemId");

                    b.HasIndex("Flagged");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_line_item", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.LawFirm", b =>
                {
                    b.Property<long>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FirmId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PracticeFocus")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("FirmId");

                    b.HasIndex("Name");

                    b.ToTable("law_firm", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Matter", b =>
                {
                    b.Property<long>("MatterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MatterId"));

                    b.Property<decimal>("BudgetAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long?>("FirmId")
                        .HasColumnType("bigint");

                    b.Property<string>("MatterNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MatterType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("date");

                    b.Property<int>("PracticeAreaId")
                        .HasColumnType("integer");

                    b.Property<long>("ResponsibleStaffId")
                        .HasColumnType("bigint");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MatterId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FirmId");

                    b.HasIndex("MatterNumber")
                        .IsUnique();

                    b.HasIndex("OpenDate");

                    b.HasIndex("PracticeAreaId");

                    b.HasIndex("ResponsibleStaffId");

                    b.HasIndex("Status");

                    b.ToTable("matter", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.MatterBudget", b =>
                {
                    b.Property<long>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BudgetId"));

                    b.Property<decimal>("BudgetAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("BudgetId");

                    b.HasIndex("MatterId");

                    b.ToTable("matter_budget", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.MatterEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<long?>("ActorStaffId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.HasKey("EventId");

                    b.HasIndex("ActorStaffId");

                    b.HasIndex("MatterId", "EventDate");

                    b.ToTable("matter_event", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.PracticeArea", b =>
                {
                    b.Property<int>("PracticeAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PracticeAreaId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("PracticeAreaId");

                    b.ToTable("practice_area", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Staff", b =>
                {
                    b.Property<long>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StaffId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BarJurisdiction")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("StaffId");

                    b.HasIndex("FullName");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<long>("TimeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TimeEntryId"));

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("MatterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("MatterId");

                    b.HasIndex("StaffId");

                    b.ToTable("time_entry", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.UtbmsCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("CodeType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PracticeArea")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Code");

                    b.ToTable("utbms_code", (string)null);
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Approval", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Staff", "ApproverStaff")
                        .WithMany("Approvals")
                        .HasForeignKey("ApproverStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApproverStaff");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Contract", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("Contracts")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Deadline", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Contract", "Contract")
                        .WithMany("Deadlines")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("Deadlines")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Staff", "OwnerStaff")
                        .WithMany("OwnedDeadlines")
                        .HasForeignKey("OwnerStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");

                    b.Navigation("Matter");

                    b.Navigation("OwnerStaff");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Document", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Contract", "Contract")
                        .WithMany("Documents")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("Documents")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Staff", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");

                    b.Navigation("Matter");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.LawFirm", "Firm")
                        .WithMany("Invoices")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("Invoices")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firm");

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Matter", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Client", "Client")
                        .WithMany("Matters")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.LawFirm", "Firm")
                        .WithMany("Matters")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.PracticeArea", "PracticeArea")
                        .WithMany("Matters")
                        .HasForeignKey("PracticeAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Staff", "ResponsibleStaff")
                        .WithMany("ResponsibleMatters")
                        .HasForeignKey("ResponsibleStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Firm");

                    b.Navigation("PracticeArea");

                    b.Navigation("ResponsibleStaff");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.MatterBudget", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("Budgets")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.MatterEvent", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Staff", "ActorStaff")
                        .WithMany()
                        .HasForeignKey("ActorStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("Events")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorStaff");

                    b.Navigation("Matter");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Matter", "Matter")
                        .WithMany("TimeEntries")
                        .HasForeignKey("MatterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalMatterContractPortal.Domain.Entities.Staff", "Staff")
                        .WithMany("TimeEntries")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matter");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Client", b =>
                {
                    b.Navigation("Matters");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Deadlines");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.LawFirm", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Matters");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Matter", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Contracts");

                    b.Navigation("Deadlines");

                    b.Navigation("Documents");

                    b.Navigation("Events");

                    b.Navigation("Invoices");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.PracticeArea", b =>
                {
                    b.Navigation("Matters");
                });

            modelBuilder.Entity("LegalMatterContractPortal.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("OwnedDeadlines");

                    b.Navigation("ResponsibleMatters");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
